apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.job.name }}
  namespace: {{ .Values.nameOverride }}
spec:
  schedule: "0 /8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          containers:
          - name: {{ .Values.container.name }}
            image: {{ .Values.image.repository }}
            env:
              - name: AWS_DEFAULT_REGION
                value: {{ .Values.cluster.region }}
              - name: CLUSTER_NAME
                value: {{ .Values.cluster.name }}
              - name: EXCLUDE_NAMESPACES
                value: {{ .Values.exclude }}
              - name: SECRET_NAME
                value: {{ .Values.ecrsecret.name }}
            command:
              - bash
              - "-c"
              - |
                AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
                TOKEN=$(aws ecr --region=$AWS_DEFAULT_REGION get-authorization-token --output text --query authorizationData[].authorizationToken | base64 -d | cut -d: -f2)     
                NAMESPACES=$(kubectl get ns -o jsonpath="{.items[*].metadata.name}")
                for NS in ${NAMESPACES[@]}; do
                  if [[ "${EXCLUDE_NAMESPACES[@]} " =~ " ${NS} " ]]; then
                      echo "-> Skipping namespace: $NS"
                      continue
                  fi

                  echo "-> Refreshing secrets in namespace: $NS"
                  kubectl -n $NS delete secret --ignore-not-found "$SECRET_NAME"
                  kubectl -n $NS create secret docker-registry "$SECRET_NAME" --docker-server=https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com --docker-username=AWS --docker-password="$TOKEN" "
                  echo
                done
          restartPolicy: OnFailure
