apiVersion: v1
kind: Secret
metadata:
  name: {{ include "refresh-ecr-token.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "refresh-ecr-token.serviceAccountName" . }}
type: kubernetes.io/service-account-token