{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "refresh-ecr-token.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
secrets:
  - name: {{ include "refresh-ecr-token.fullname" . }}
{{- end }}