apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterrole.secret.name }}
  namespace: {{ .Values.nameOverride }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.clusterrole.serviceaccount.name }}
type: kubernetes.io/service-account-token