# Default values for ecrsecrets.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: mhrznamn068/awscli-kubectl-helm-tf:latest
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
excludeNamespaces:    #namespaces to be skipped for creating secrets
  - kube-node-lease
  - kube-public
  - default
  - kube-system

clusterrole:
  name: 
  serviceaccount:
    name: 
  secret:
    name : 
clusterrolebinding:
  name: 

job:
  name: 

container:
  name: 

cluster: 
  region: 
  name: 
secret:
  name: 

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
nodeSelector: {}

tolerations: []

affinity: {}
